#!/bin/bash

declare -i connect_timeout=2 transfer_timeout=2 max_redirs=2
declare -i last_check_max_diff=60
declare -r NAGIOS_SUCCESS=0 NAGIOS_WARNING=1 NAGIOS_CRITICAL=2 NAGIOS_UNKNOWN=3
declare -a accepted_opt_names=( connect_timeout transfer_timeout max_redirs last_check_max_diff )
declare -a received_options

cache_dir="/var/cache/check-connectivity"
tag_name="connectivity"

usage() {
  local prog=$(basename $0)
  echo "
Usage: $prog <-4 | -6> [ OPTIONS ] <-c n_critical> <-w n_warning> <url1> [ url2 ] [ ... ] [ urlN ]

  Options:
    -4               check IPv4 connectivity
    -6               check IPv6 connectivity
    -D <cache_dir>   directory where to cache connectivity information
    -T <tag_name>    name to use as the cache file
    -N               disable cache (don't cache the result)
    -d               enable debug mode
    -O name=value    set the given option name to the specified value
                     Accepted names:
                         connect_timeout (is)
                         transfer_timeout (is)
                         max_redirs (i)
                         last_check_max_diff (is)

                     Expected value format:
                         (is = integer seconds, i = integer)

"
  exit 1
}

error() {
  local msg="$1"
  local ret=${2:-$NAGIOS_UNKNOWN}

  echo "Error: $msg" 1>&2
  exit $ret
}

is_number() {
  local n="$1"

  if [[ $n =~ ^[0-9]+$ ]]; then
    return 0
  else
    return 1
  fi
}

is_in_array() {
  local value="$1"
  shift
  local array="$2"
  local v

  for v in "$@"; do
    if [ "$v" == "$value" ]; then
      return 0
    fi
  done

  return 1
}

warn() {
  msg="$1"
  
  echo "Warning: $msg" 1>&2
}

# main

unset n_failed n_critical user_def_tag use_cache disable_cache
getopt_flags='46dc:D:w:O:N'
proto=''
while getopts $getopt_flags OPTNAME; do
  case $OPTNAME in
    [46])
      if [ -n "$proto" -a "-$proto" != "-$OPTNAME" ]; then
        error "either -4 or -6 should be used, not both"
      else
        proto="-$OPTNAME"
      fi
      ;;
    c)
      if is_number $OPTARG; then
        n_critical=$OPTARG
      else
        error "argument to -c must be an integer >= 0"
      fi
      ;;
    w)
      if is_number $OPTARG; then
        n_warning=$OPTARG
      else
        error "argument to -w must be an integer >= 0"
      fi
      ;;
    d)
      set -x
      ;;
    D)
      cache_dir="$OPTARG"
      ;;
    T)
      tag_name="$OPTARG"
      user_def_tag=1
      ;;
    N)
      disable_cache=1
      ;;
    O)
      IFS=, read -a received_options <<< "$OPTARG"
      for name_val in ${received_options[@]}; do
        if ! [[ "$name_val" =~ ^([A-Za-z0-9_]+)=(.+) ]]; then
          warn "skipping invalid option '$name_val'"
          continue
        fi

        opt_name=${name_val%%=*}
        opt_value=${name_val##*=}

        if is_in_array "$opt_name" ${accepted_opt_names[@]}; then
          eval "$opt_name"="$opt_value"
        else
          warn "skipping invalid option name '$opt_name'"
        fi
      done
        ;;
    *)
      exit $NAGIOS_UNKNOWN
      ;;
  esac
done

[ $OPTIND -gt 1 ] && shift $(( $OPTIND - 1 ))

[ $# -eq 0 ] && usage

if ! hash curl &>/dev/null ; then
  error "unable to find the curl executable. This script depends on "\
"curl being installed and on the PATH"
fi

if [ -z "$n_critical" ]; then
  error "missing command line option -c"
elif [ $n_critical -gt $# ]; then
  error "the number of failed attempts can't be greater than the "\
"number of urls"
elif [ -z "$n_warning" ]; then
  error "missing command line option -w"
elif [ $n_warning -gt $# ]; then
  error "the number of warning attempts can't be greater than the "\
"number of urls"
elif [ $n_critical -eq $n_warning ]; then
  error "the warning (-w) and critical (-c) values can't be equal"
fi

if [ -z "$proto" ]; then
  error "you need to specify either -4 (for ipv4) or -6 (for ipv6)"
fi

if [ -z "$user_def_tag" -a "$proto" == "-4" ]; then
  tag_name+="_ipv4"
elif [ -z "$user_def_tag" -a "$proto" == "-6" ]; then
  tag_name+="_ipv6"
fi

cache_file="$cache_dir/$tag_name"

# cache is enabled, cache_dir exists and is writable and
# cache file is a link or not exists
if [ -z "$disable_cache" -a -d "$cache_dir" -a -w "$cache_dir" ] && [ -L "$cache_file" -o ! -e "$cache_file" ]; then
  use_cache=1
elif [ -z "$disable_cache" -a ! -e "$cache_dir" ]; then
  mkdir "$cache_dir"
  if [ $? -ne 0 ]; then
    warn "unable to create cache_dir '$cache_dir'. Skipping caching..."
  fi
elif [ -z "$disable_cache" -a ! -d "$cache_dir" ]; then
  warn "cache_dir path '$cache_dir' exists but is not a directory. Skipping caching..."
elif [ -z "$disable_cache" -a -e "$cache_file" -a ! -L "$cache_file" ]; then
  warn "cache_file path '$cache_file' exists but is not a symlink. Skipping caching..."
fi

if [ -n "$use_cache" -a -L "$cache_file" ]; then
  status_str=$(readlink "$cache_file")
  if [ $? -ne 0 ]; then
    warn "unable to read from cache file"
  elif ! [[ "$status_str" =~ ^[0123]:[0-9]+$ ]]; then
    warn "data from cache file is not in the desired format (exit_code:epoch)"
  else
    # the cache string is the contents of the link de-referenced
    # it should be in the format: exit_code:epoch, e.g.: 0:1372741914
    last_status=${status_str%%:*}
    last_check_time=${status_str##*:}

    now=$(date +%s)
    if [ $? -ne 0 ]; then
      error "unable to determine current time"
    fi

    if [ $(( $now - $last_check_time )) -le $last_check_max_diff ]; then
      exit $last_status
    fi
  fi
fi

declare -i n_failed=0 n_left=$#
while [ $n_left -gt 0 -a -n "$1" ]; do
  n_left=$(( $n_left - 1 ))
  test_url="$1"
  curl $proto --connect-timeout $connect_timeout --max-time $transfer_timeout \
    -L --max-redirs $max_redirs --retry 0 -o /dev/null -s "$test_url"
  status=$?
  if [ $status -eq 0 -a $(( $n_left + $n_failed )) -lt $n_critical  ]; then
    # even if next tests fail, it won't reach $n_critical
    # so no need to test anymore
    break
  elif [ $status -ne 0 -a $n_failed -eq $n_critical ]; then
    # too many failures, don't need to test anymore
    break
  fi

  shift
done

if [ $n_critical -gt 0 -a $n_failed -eq $n_critical ]; then
  exit_code=$NAGIOS_CRITICAL
elif [ $n_warning -gt 0 -a $n_failed -ge $n_warning ]; then
  exit_code=$NAGIOS_WARNING
else
  exit_code=$NAGIOS_SUCCESS
fi

if [ -n "$use_cache" ]; then
  now=$(date +%s)
  if [ $? -ne 0 ]; then
    error "unable to determine current time"
  fi

  if [ -n "$use_cache" ] && ! ln -sf "$exit_code:$now" "$cache_file"; then
    warn "unable to link to cache file '$cache_file'"
  fi
fi

exit $exit_code
